### ISSUE TITLE
Lattice Parameterization Inconsistency

### ISSUE THREAD

**Issue by DIvanov503** [cs-au-dk/TIP#15]
In the file `GenericLattices.scala` the powerset lattice is parameterized by a characteristic function ch:
`class PowersetLattice[A](ch: A => Boolean) extends Lattice`
At the same time, the reverse powerset lattice has Set(A) as a parameter:
`class ReversePowersetLattice[A](s: Set[A]) extends Lattice`
Probably, the class `PowersetLattice` should be changed as follows:
`class PowersetLattice[A](s: Set[A]) extends Lattice`

**Comment by algobardo** [comment]
I think the right change would rather be on the `ReversePowersetLattice`.
Note that the approach of using the characteristic function still allows you to pass a Set to construct the lattice as `Set[A]` extends `(A) => Boolean`: http://www.scala-lang.org/api/2.12.3/scala/collection/Set.html

**Comment by DIvanov503** [comment]
I take your point. On the other hand, Idea doesn't seem to recognize the type `A`  if I just replace `s: Set[A]` by `ch: A => Boolean` in the `ReversePowersetLattice`, e.g., it complains about the `AvailableExpAnalysis` and doesn't compile. Adding `asInstanceOf` operators fix the problem but it doesn't seem to be a good style. However, I'm a Scala novice and might have missed an elegant way of solving it.

By the way, I'm curious whether there exists a use case where defining a lattice over a subset of a type, that itself does not form a type, is needed.

**Comment by DIvanov503** [comment]
Quickfix: replacing `s: Set[A]` by `ch: A => Boolean` works well for my reaching definitions analysis implementation. However, there are still typing warnings from Idea that can be eliminated by `asInstanceOf`. And it requires explicit construction of the bottom element in the `ReversePowersetLattice`.

**Comment by algobardo** [comment]
- As for the use case, having something to pass when constructing the object *save* us from annotating the generic type. Moreover if you want to be pedantic/defensive the powerset lattice implementation coud check that the lub operation is performed on sets that are subset of the one denoted by `ch`

- As for the Idea warnings, Idea scala plugin is not as clever as the scala compiler. You have to live with them. I think there is some work going on for making a Language Server for giving the editors compiler info, but I guess we have to wait for that.

**Comment by DIvanov503** [comment]
- Thank you! The lub return was one of my concerns as well.
- Thanks for clarification!
