### ISSUE TITLE
IntelliJ doesn't pick up SBT project

### ISSUE THREAD

**Issue by Herbstein** [cs-au-dk/TIP#22]
The `.idea` folder in the repository caused me many a headaches. Importing the project into IntelliJ as-is causes running `Tip.scala` to result in a `ClassNotFoundException`. Simply deleting the folder and re-importing the project fixes the issue completely.

**Comment by amoeller** [comment]
Did you follow the instructions under **IntelliJ IDEA** in https://github.com/cs-au-dk/TIP/blob/master/README.md? It worked last time I tried...
Also note that `.idea/inspectionProfiles` and `.idea/codeStyles` shouldn't be deleted.

**Comment by Herbstein** [comment]
Yeah, I did. Also tried cloning manually and importing. In both cases the third step didn't happen.

![image](https://user-images.githubusercontent.com/3884484/91875295-96998f00-ec7b-11ea-92ff-c095433bf5da.png)

![image](https://user-images.githubusercontent.com/3884484/91875342-a44f1480-ec7b-11ea-8f4b-a4000dcbfe9c.png)

For reference, this is what the project dialog looks like when I clone the repository in IntelliJ, delete `.idea`, and open the project again. 

![image](https://user-images.githubusercontent.com/3884484/91876391-e7f64e00-ec7c-11ea-93bf-dcfe0135df0f.png)

Lastly, overwriting the files in the local `.idea` folder with the contents of the version in the repository doesn't stop the project from being loaded properly. So that is my personal solution at this time. The images above are taken from the third computer I've set-up the project on. First two being well-used Linux installations, and this being a *completely* new Windows installation.

**Comment by amoeller** [comment]
Please try the latest version of TIP, see the updated "Getting started" guide at https://github.com/cs-au-dk/TIP#getting-started. 

(Unfortunately, the latest version of IntelliJ doesn't allow importing a project from version control if the .idea directory already exists. And the reload step is necessary because of another IntelliJ bug causing the classpath to be set incorrectly after import.)
