### ISSUE TITLE
Implementation missing?

### ISSUE THREAD

**Issue by kwanghoon** [cs-au-dk/TIP#23]
https://github.com/cs-au-dk/TIP/blob/a8e9428927a7116aa3f0a63a286cd3de08c347a9/src/tip/analysis/AndersenAnalysis.scala#L47

When I run 
 - ./tip -andersen ./examples/andersen.tip

I met an error, an implementation is missing at
 - tip.analysis.AndersenAnalysis.visit(AndersenAnalysis.scala:47).

Is it intended or am I missing something?

Thanks in advance.

--Kwanghoon

**Comment by amoeller** [comment]
See https://cs.au.dk/~amoeller/spa/. The open source version of TIP omits certain parts that are left for [exercises](https://github.com/cs-au-dk/TIP/wiki/TIP-exercises).

**Comment by kwanghoon** [comment]
:+1:
